SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

USE `ESRMS`;

ALTER TABLE Students ADD COLUMN ClassId int(11) NOT NULL;
ALTER TABLE Grades ADD COLUMN GradeDate datetime NOT NULL;

ALTER TABLE `Teachers` CHANGE `CreatedOn` `CreatedOn` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `Parents` CHANGE `CreatedOn` `CreatedOn` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `Students` CHANGE `CreatedOn` `CreatedOn` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `Students`
  ADD KEY `ClassId` (`ClassId`),
  ADD CONSTRAINT `Students_ibfk_3` FOREIGN KEY (`ClassId`) REFERENCES `Classes` (`ID`);

COMMIT;


