
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('Timetable').del()
    .then(function () {
      // Inserts seed entries
      return knex('Timetable').insert([
        // Class 1
        {Day: 1, Hour: '8', ClassId: 1, SubjectId: 1},
        {Day: 1, Hour: '9', ClassId: 1, SubjectId: 2},
        {Day: 1, Hour: '10', ClassId: 1, SubjectId: 3},
        {Day: 1, Hour: '11', ClassId: 1, SubjectId: 4},
        {Day: 1, Hour: '12', ClassId: 1, SubjectId: 5},
        {Day: 1, Hour: '13', ClassId: 1, SubjectId: 6},
        {Day: 2, Hour: '8', ClassId: 1, SubjectId: 1},
        {Day: 2, Hour: '9', ClassId: 1, SubjectId: 2},
        {Day: 2, Hour: '10', ClassId: 1, SubjectId: 3},
        {Day: 2, Hour: '11', ClassId: 1, SubjectId: 4},
        {Day: 2, Hour: '12', ClassId: 1, SubjectId: 5},
        {Day: 3, Hour: '8', ClassId: 1, SubjectId: 1},
        {Day: 3, Hour: '9', ClassId: 1, SubjectId: 2},
        {Day: 3, Hour: '10', ClassId: 1, SubjectId: 3},
        {Day: 3, Hour: '11', ClassId: 1, SubjectId: 4},
        {Day: 3, Hour: '12', ClassId: 1, SubjectId: 5},
        {Day: 4, Hour: '8', ClassId: 1, SubjectId: 1},
        {Day: 4, Hour: '9', ClassId: 1, SubjectId: 2},
        {Day: 4, Hour: '10', ClassId: 1, SubjectId: 3},
        {Day: 4, Hour: '11', ClassId: 1, SubjectId: 4},
        {Day: 4, Hour: '12', ClassId: 1, SubjectId: 5},
        {Day: 4, Hour: '13', ClassId: 1, SubjectId: 6},
        {Day: 5, Hour: '8', ClassId: 1, SubjectId: 1},
        {Day: 5, Hour: '9', ClassId: 1, SubjectId: 2},
        {Day: 5, Hour: '10', ClassId: 1, SubjectId: 3},
        {Day: 5, Hour: '11', ClassId: 1, SubjectId: 4},
        {Day: 5, Hour: '12', ClassId: 1, SubjectId: 5},
        {Day: 5, Hour: '13', ClassId: 1, SubjectId: 6},

        // Class 2
        {Day: 1, Hour: '8', ClassId: 2, SubjectId: 1},
        {Day: 1, Hour: '9', ClassId: 2, SubjectId: 2},
        {Day: 1, Hour: '10', ClassId: 2, SubjectId: 3},
        {Day: 1, Hour: '11', ClassId: 2, SubjectId: 4},
        {Day: 1, Hour: '12', ClassId: 2, SubjectId: 5},
        {Day: 1, Hour: '13', ClassId: 2, SubjectId: 6},
        {Day: 2, Hour: '8', ClassId: 2, SubjectId: 1},
        {Day: 2, Hour: '9', ClassId: 2, SubjectId: 2},
        {Day: 2, Hour: '10', ClassId: 2, SubjectId: 3},
        {Day: 2, Hour: '11', ClassId: 2, SubjectId: 4},
        {Day: 2, Hour: '12', ClassId: 2, SubjectId: 5},
        {Day: 3, Hour: '8', ClassId: 2, SubjectId: 1},
        {Day: 3, Hour: '9', ClassId: 2, SubjectId: 2},
        {Day: 3, Hour: '10', ClassId: 2, SubjectId: 3},
        {Day: 3, Hour: '11', ClassId: 2, SubjectId: 4},
        {Day: 3, Hour: '12', ClassId: 2, SubjectId: 5},
        {Day: 4, Hour: '8', ClassId: 2, SubjectId: 1},
        {Day: 4, Hour: '9', ClassId: 2, SubjectId: 2},
        {Day: 4, Hour: '10', ClassId: 2, SubjectId: 3},
        {Day: 4, Hour: '11', ClassId: 2, SubjectId: 4},
        {Day: 4, Hour: '12', ClassId: 2, SubjectId: 5},
        {Day: 4, Hour: '13', ClassId: 2, SubjectId: 6},
        {Day: 5, Hour: '8', ClassId: 2, SubjectId: 1},
        {Day: 5, Hour: '9', ClassId: 2, SubjectId: 2},
        {Day: 5, Hour: '10', ClassId: 2, SubjectId: 3},
        {Day: 5, Hour: '11', ClassId: 2, SubjectId: 4},
        {Day: 5, Hour: '12', ClassId: 2, SubjectId: 5},
        {Day: 5, Hour: '13', ClassId: 2, SubjectId: 6},

        // Class 3
        {Day: 1, Hour: '8', ClassId: 3, SubjectId: 1},
        {Day: 1, Hour: '9', ClassId: 3, SubjectId: 2},
        {Day: 1, Hour: '10', ClassId: 3, SubjectId: 3},
        {Day: 1, Hour: '11', ClassId: 3, SubjectId: 4},
        {Day: 1, Hour: '12', ClassId: 3, SubjectId: 5},
        {Day: 1, Hour: '13', ClassId: 3, SubjectId: 6},
        {Day: 2, Hour: '8', ClassId: 3, SubjectId: 1},
        {Day: 2, Hour: '9', ClassId: 3, SubjectId: 2},
        {Day: 2, Hour: '10', ClassId: 3, SubjectId: 3},
        {Day: 2, Hour: '11', ClassId: 3, SubjectId: 4},
        {Day: 2, Hour: '12', ClassId: 3, SubjectId: 5},
        {Day: 3, Hour: '8', ClassId: 3, SubjectId: 1},
        {Day: 3, Hour: '9', ClassId: 3, SubjectId: 2},
        {Day: 3, Hour: '10', ClassId: 3, SubjectId: 3},
        {Day: 3, Hour: '11', ClassId: 3, SubjectId: 4},
        {Day: 3, Hour: '12', ClassId: 3, SubjectId: 5},
        {Day: 4, Hour: '8', ClassId: 3, SubjectId: 1},
        {Day: 4, Hour: '9', ClassId: 3, SubjectId: 2},
        {Day: 4, Hour: '10', ClassId: 3, SubjectId: 3},
        {Day: 4, Hour: '11', ClassId: 3, SubjectId: 4},
        {Day: 4, Hour: '12', ClassId: 3, SubjectId: 5},
        {Day: 4, Hour: '13', ClassId: 3, SubjectId: 6},
        {Day: 5, Hour: '8', ClassId: 3, SubjectId: 1},
        {Day: 5, Hour: '9', ClassId: 3, SubjectId: 2},
        {Day: 5, Hour: '10', ClassId: 3, SubjectId: 3},
        {Day: 5, Hour: '11', ClassId: 3, SubjectId: 4},
        {Day: 5, Hour: '12', ClassId: 3, SubjectId: 5},
        {Day: 5, Hour: '13', ClassId: 3, SubjectId: 6},
      ]);
    });
};
